name: Playwright Tests with Allure Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16 # Change this to your desired Node.js version
        cache: 'npm'
      
    - name: Install dependencies
      run: npm ci

    - name: Run Playwright tests and generate Allure results
      run: |
        npx playwright install
        npx playwright test --reporter=list,json --reporter-options=output=allure-results/allure-result.json

    - name: Upload Allure results as artifact
      uses: actions/upload-artifact@v2
      with:
        name: allure-results
        path: allure-results

    - name: Generate Allure report
      uses: simple-elf/allure-report-action@master
      with:
        allure_results: allure-results
        allure_report: allure-report
        allure_history: allure-history

    - name: Deploy Allure report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-report
